### PR TITLE
feat: login user flow arch

### PR DESCRIPTION
**Pull request by JudeDavis1**
Basic user flow architecture.

### CODE REVIEW

**Comment by JudeDavis1** [comment]
Just let me know what you think of this design first, don't merge just yet. VSCode has an inbuilt drawio editor so you can open it there and check it out.

**Review by j-koziel — CHANGES_REQUESTED** [review]
So far so good... verification for new admins is a good idea. For new users signing up I think the admin could just generate like a token (kind of like an api token) to verify that they belong to that cong. We can expand on the ideas we discussed

**Comment by j-koziel** [comment]
I've converted this one to draft because it looks like you're still working on it :)

**Comment by JudeDavis1** [comment]
@j-koziel This should be ready now. It's a bit incomplete but contains the main idea.

**Comment by JudeDavis1** [comment]
> So far so good... verification for new admins is a good idea. For new users signing up I think the admin could just generate like a token (kind of like an api token) to verify that they belong to that cong. We can expand on the ideas we discussed

Why is this requested change lol I thought it included that idea?

**Comment by j-koziel** [comment]
> > So far so good... verification for new admins is a good idea. For new users signing up I think the admin could just generate like a token (kind of like an api token) to verify that they belong to that cong. We can expand on the ideas we discussed
> 
> Why is this requested change lol I thought it included that idea?

I just clicked on requested changes because the pr wasn't ready yet :)

**Review by j-koziel — APPROVED** [review]
looks good

**Pull request merged**
