### PR TITLE
chore(more linting): linting in actions

### LINKED ISSUE #49: Create formatting/linting configs for FE and BE
Create some formatting and linting configs so that code styles are consistent everywhere.

### PR DESCRIPTION
**Pull request by j-koziel**
~~This PR introduces husky~~

This PR introduces linting in github actions

### CODE REVIEW

**Comment by j-koziel** [comment]
So right now the problem is with vsfptd (or something like that) requires a prompt during the docker build... I've tried copying in a default config in https://github.com/cm-core-team/cm-core/pull/75/commits/9cf05051b35f487e686550255c11d50a6ec299b0 but that hasn't worked

**Comment by JudeDavis1** [comment]
put this back in progress cause we need to look at this again later

**Comment by j-koziel** [comment]
As you can see from my last ~10 commits this took way longer than it was supposed to

**Review by JudeDavis1 — APPROVED** [review]
Simply amazing, great work. LGTM

**Pull request merged**
